routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// LOGIN
Route::get('login','App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login','App\Http\Controllers\AuthController@proses_login')->name('proses_login');

Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['cek_login:admin']], function () {
        Route::get('admin','App\Http\Controllers\AdminController@index')->name('admin');
        Route::get('adminkar', 'App\Http\Controllers\KaryawanController@adminkar')->name('adminkar');
        Route::resource('datakar', 'App\Http\Controllers\KaryawanController');
    }); 
    Route::group(['middleware' => ['cek_login:pemilik']], function () {
        Route::get('pemilik','App\Http\Controllers\PemilikController@index')->name('pemilik');
    }); 
    Route::group(['middleware' => ['cek_login:karyawan']], function () {
        Route::get('/karyawan', function () {
            return view('karyawan.karyawan');
        })->name('karyawan');
    }); 
    Route::group(['middleware' => ['cek_login:kasir']], function () {
        Route::get('kasir','App\Http\Controllers\KasirController@index')->name('kasir');
    });   
});

//REGISTER
Route::get('register', 'App\Http\Controllers\RegisterController@create')->name('register');
Route::post('register', 'App\Http\Controllers\RegisterController@store')->name('register');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('bagian', 'App\Http\Controllers\BagianController');

//  AKUN
Route::get('akun', 'App\Http\Controllers\AkunController@index')->name('akun');

//SUPPLIER
Route::resource('supplier', 'App\Http\Controllers\SupplierController');
Route::get('/cetak_pdf/supplier', 'App\Http\Controllers\SupplierController@cetak_pdf');

//SUPPLYBARANG
Route::resource('supplybarang', 'App\Http\Controllers\SupplyBarangController');
Route::get('/cetak_pdf/supplybarang', 'App\Http\Controllers\SupplyBarangController@cetak_pdf');

//KERUSAKAN
Route::resource('returnbarang', 'App\Http\Controllers\ReturnBarangController');
Route::get('/cetak_pdf/returnbarang', 'App\Http\Controllers\ReturnBarangController@cetak_pdf');

// //MENU
Route::get('/menu/get', 'App\Http\Controllers\MenuMakananController@byKategori')->name('menu.bykategori');
Route::resource('menumakanan', 'App\Http\Controllers\MenuMakananController');
Route::get('/cetak_pdf/menumakanan', 'App\Http\Controllers\MenuMakananController@cetak_pdf');

//KASIR
Route::resource('/transaksi', 'App\Http\Controllers\TransaksiController');
Route::get('/cetak_pdf/transaksi', 'App\Http\Controllers\TransaksiController@cetak_pdf');

// //ABSENSI
Route::resource('/absensi', 'App\Http\Controllers\AbsensiController');

//PEMILIK
Route::resource('/p_supplier', 'App\Http\Controllers\P_SupController');
Route::resource('/p_menumakanan', 'App\Http\Controllers\P_MenuController');
// Route::resource('/pemasukan', 'App\Http\Controllers\P_PemasukanController');
Route::get('/pemasukan/{cabang}/{bulan}/{tahun}', 'App\Http\Controllers\P_PemasukanController@index')->name('getPemasukan');
Route::resource('/pengeluaran', 'App\Http\Controllers\P_PengeluaranController');

Route::get('/grafik/{tahun}', 'App\Http\Controllers\P_GrafikController@index');
Route::get('/grafikMakananFavorit', 'App\Http\Controllers\P_grafikmmController@index')->name('grafikmm');
Route::get('/getDataGrafikPendapata ', 'App\Http\Controllers\P_GrafikController@getDataGrafikPendapata')->name('getDataGrafikPendapata');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>@yield('title')</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	<!-- <link rel="icon" href="{{asset('/assets/img/icon.ico')}}" type="image/x-icon"/> -->
	<link rel="icon" href="{{asset('/assets/img/iconku.png')}}" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<script src="{{asset('assets/js/plugin/webfont/webfont.min.js')}}"></script>
	<script>
		WebFont.load({
			google: {"families":["Lato:300,400,700,900"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['{{asset('assets/css/fonts.min.css')}}']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>

	<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/atlantis.min.css')}}">
	<!-- <link href="{{asset('assets/styles.css')}}" rel="stylesheet" /> -->
	<!-- <link href="{{asset('assets/prism.css')}}" rel="stylesheet" /> -->
	<script src="{{asset('js/jquery-3.5.1.js')}}"></script>
	<script src="{{asset('js/jquery.dataTables.min.js')}}"></script>
	<script src="{{asset('js/dataTables.bootstrap4.min.js')}}"></script>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
</head>
<body>
	<div class="wrapper">
		<div class="main-header">
			<div class="logo-header" data-background-color="light-blue2">
			<a href="#" class="logo">
					<img width="150px" height="auto" src="{{asset('assets/img/logoku.png')}}" alt="navbar brand" class="navbar-brand">
				</a>
				<button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon">
						<i class="icon-menu"></i>
					</span>
				</button>
				<button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
				<div class="nav-toggle">
					<button class="btn btn-toggle toggle-sidebar">
						<i class="icon-menu"></i>
					</button>
			    </div>
		    </div>
			<nav class="navbar navbar-header navbar-expand-lg" data-background-color="light-blue2">
				<div class="container-fluid">
					<ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
						<li class="nav-item">
						<a class="dropdown-item text-light" href="{{url('logout')}}">Logout</a>
						</li>
					</ul>
				</div>
			</nav>
		</div>
        @include('sidebar')
		<div class="main-panel">
			<div class="content content-documentation">
				<div class="container-fluid">
					<div class="card card-documentation">
						<div class="card-header bg-info-gradient text-white bubble-shadow">
							@yield('header')
						</div>

						<div class="card-body">
							@yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

	@include('sweetalert::alert')

</body>

<script src="{{asset('assets/js/core/jquery.3.2.1.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}"></script>
<script src="{{asset('assets/js/core/popper.min.js')}}"></script>
<script src="{{asset('assets/js/core/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/chart.js/chart.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/plugin/jqvmap/jquery.vmap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/plugin/jqvmap/maps/jquery.vmap.world.js')}}" charset="utf-8"></script>
<script src="{{asset('assets/js/plugin/chart-circle/circles.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>
<script src="{{asset('assets/js/atlantis.min.js')}}"></script>
<script src="{{asset('assets/prism.js')}}"></script>
<script src="{{asset('assets/prism-normalize-whitespace.min.js')}}"></script>
   <!-- Datatables -->
   <script src="{{asset('assets/js/plugin/datatables/datatables.min.js')}}"></script>

        <script src="{{asset('js/select2.js')}}"></script>
@yield('script')
<script type="text/javascript">
	// Optional
	Prism.plugins.NormalizeWhitespace.setDefaults({
		'remove-trailing': true,
		'remove-indent': true,
		'left-trim': true,
		'right-trim': true,
	});
	
	// handle links with @href started with '#' only
	$(document).on('click', 'a[href^="#"]', function(e) {
		// target element id
		var id = $(this).attr('href');

		// target element
		var $id = $(id);
		if ($id.length === 0) {
			return;
		}

		// prevent standard hash navigation (avoid blinking in IE)
		e.preventDefault();

		// top position relative to the document
		var pos = $id.offset().top - 80;

		// animated top scrolling
		$('body, html').animate({scrollTop: pos});
	});
</script>

@stack('modals')
@stack('script')
</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>Form Login</title>
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js"
            crossorigin="anonymous"></script>
            <link rel="icon" href="{{asset('/assets/img/iconku.png')}}" type="image/x-icon"/>
    </head>
    </br></br>
    <body style="background-image: url('{{asset('/assets/img/bg.jpeg')}}'); background-repeat:no-repeat; background-size: cover; ">        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-5">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    {{-- Error Alert --}}
                                    @if(session('error'))
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{session('error')}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    @endif
                                    <div class="card-header">
                                        <h3 class="text-center font-weight-light my-4">Silahkan Login !</h3>
                                    </div>
                                    <div class="card-body">
                                        <form action="{{url('proses_login')}}" method="POST" id="logForm">
                                            {{ csrf_field() }}
                                            <div class="form-group">
                                                @error('login_gagal')
                                                    {{-- <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span> --}}
                                                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                                        {{-- <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span> --}}
                                                        <span class="alert-inner--text"><strong>Warning!</strong> {{ $message }}</span>
                                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    @enderror
                                                <label class="small mb-1" for="inputEmailAddress">Username</label>
                                                <input
                                                    class="form-control py-4"
                                                    id="inputEmailAddress"
                                                    name="username"
                                                    type="text"
                                                    placeholder="Masukkan Username"/>
                                                @if($errors->has('username'))
                                                <span class="error">{{ $errors->first('username') }}</span>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputPassword">Password</label>
                                                <input
                                                    class="form-control py-4"
                                                    id="inputPassword"
                                                    type="password"
                                                    name="password"
                                                    placeholder="Masukkan Password"/>
                                                @if($errors->has('password'))
                                                <span class="error">{{ $errors->first('password') }}</span>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox">
                                                    <input class="custom-control-input" id="rememberPasswordCheck" type="checkbox"/>
                                                    <label class="custom-control-label" for="rememberPasswordCheck">Remember password</label>
                                                </div>
                                            </div>
                                            <div
                                                class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                                {{-- <a class="small" href="#">Forgot Password?</a> --}}
                                                <button class="btn btn-secondary" type="submit">Login</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="small">
                                            {{-- <a href="{{url('register')}}">Belum Punya Akun? Daftar!</a> --}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
 
        </div>
        <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            crossorigin="anonymous"></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
        <script src="{{url('assets/js/scripts.js')}}"></script>
    </body>
</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/sidebar.blade.php
<div class="sidebar sidebar-style-2">
			<div class="sidebar-background"></div>
			<div class="sidebar-wrapper scrollbar scrollbar-inner">
				<div class="sidebar-content">
				@if(Auth::user()->level == 'admin')
				<!-- admin -->
					<ul class="nav nav-info">
						<li class="nav-item active">
							<a href="#">
								<i class="fas fa-home"></i>
								<p>Admin : {{Auth::user()->name}}</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('admin') }}">
								<p>Home</p>
							</a>
						</li>
						</li><li class="nav-item">
							<a href="{{ route('supplier.index') }}">
								<p>Supplier</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('supplybarang.index') }}">
								<p>Supply Barang</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('returnbarang.index') }}">
								<p>Return Barang</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('menumakanan.index') }}">
								<p>Kelola Menu Makanan</p>
							</a>
						</li>
						<!-- <li class="nav-item dropdown">
							<a class="nav-link nav-dropdown-toggle" href="#">Kelola Karyawan</a>
							<ul class="nav-dropdown-items">
								<li clas="nav-item"><a class="nav-link" href="{{ route('adminkar') }}">Data Karyawan</a></li>
								<li clas="nav-item"><a class="nav-link" href="#">Absensi</a></li>
								<li clas="nav-item"><a class="nav-link" href="{{ route('bagian.index') }}">Bagian</a></li>
							</ul>
						</li> -->
						<!-- <li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Dropdown link
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<a class="dropdown-item" href="#">Action</a>
								<a class="dropdown-item" href="#">Another action</a>
								<a class="dropdown-item" href="#">Something else here</a>
							</div>
						</li>
						<li class="nav-item">
							<a href="components/alerts.html">
								<p>Kelola Gaji</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('akun') }}">
								<p>Kelola Akun</p>
							</a>
						</li>
					</ul> -->
					@elseif(Auth::user()->level == 'pemilik')
					<!-- pemilik -->
					<ul class="nav nav-info">
						<li class="nav-item active">
							<a href="#">
								<i class="fas fa-home"></i>
								<p>Pemilik : {{Auth::user()->name}}</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('pemilik') }}">
								<p>Home</p>
							</a>
						</li>
						<!-- <li class="nav-item">
							<a href="components/alerts.html">
								<p>Kinerja Karyawan</p>
							</a>
						</li> -->
						<li class="nav-item">
							<a href="{{ route('p_supplier.index') }}">
								<p>Supplier</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('p_menumakanan.index') }}">
								<p>Menu Makanan</p>
							</a>
						</li>
						<li class="nav-item nav-dropdown">
							<a class="nav-link nav-dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Laporan
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								<!-- <li class="nav-item"><a class="nav-link" href="#">Laporan Gaji</a></li> -->
								<a class="dropdown-item" href="{{ route('getPemasukan',['all','all','all']) }}">Laporan Pemasukan</a>
								<a class="dropdown-item" href="{{ route('pengeluaran.index') }}">Laporan Pengeluaran</a>
								<a class="dropdown-item" href="{{ url('grafik').'/'.date('Y')}}">Grafik Pendapatan</a>
								<a class="dropdown-item" href="{{  url('grafikMakananFavorit')  }}">Grafik Menu Favorit</a>
							</div>
							
						</li>
					</ul>
					@elseif(Auth::user()->level == 'kasir')
					<!-- kasir -->
					<ul class="nav nav-info">
						<li class="nav-item active">
							<a href="#">
								<i class="fas fa-home"></i>
								<p>Kasir : {{Auth::user()->name}} </p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('kasir') }}">
								<p>Home</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('transaksi.create') }}">
								<p>Transaksi Penjualan</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('transaksi.index') }}">
								<p>Rekap</p>
							</a>
						</li>
					</ul>
					@else
					<!-- karyawan -->
					<ul class="nav nav-info">
						<li class="nav-item active">
							<a href="#">
								<i class="fas fa-home"></i>
								<p>Karyawan</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('karyawan') }}">
								<p>Home</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{ route('absensi.index') }}">
								<p>Absensi</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="components/alerts.html">
								<p>Gaji</p>
							</a>
						</li>
					</ul>
					@endif
				</div>
			</div>
		</div>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>