routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// LOGIN
Route::get('login','App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login','App\Http\Controllers\AuthController@proses_login')->name('proses_login');

Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['cek_login:admin']], function () {
        Route::get('admin','App\Http\Controllers\AdminController@index')->name('admin');
        Route::get('adminkar', 'App\Http\Controllers\KaryawanController@adminkar')->name('adminkar');
        Route::resource('datakar', 'App\Http\Controllers\KaryawanController');
    }); 
    Route::group(['middleware' => ['cek_login:pemilik']], function () {
        Route::get('pemilik','App\Http\Controllers\PemilikController@index')->name('pemilik');
    }); 
    Route::group(['middleware' => ['cek_login:karyawan']], function () {
        Route::get('/karyawan', function () {
            return view('karyawan.karyawan');
        })->name('karyawan');
    }); 
    Route::group(['middleware' => ['cek_login:kasir']], function () {
        Route::get('kasir','App\Http\Controllers\KasirController@index')->name('kasir');
    });   
});

//REGISTER
Route::get('register', 'App\Http\Controllers\RegisterController@create')->name('register');
Route::post('register', 'App\Http\Controllers\RegisterController@store')->name('register');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('bagian', 'App\Http\Controllers\BagianController');

//  AKUN
Route::get('akun', 'App\Http\Controllers\AkunController@index')->name('akun');

//SUPPLIER
Route::resource('supplier', 'App\Http\Controllers\SupplierController');
Route::get('/cetak_pdf/supplier', 'App\Http\Controllers\SupplierController@cetak_pdf');

//SUPPLYBARANG
Route::resource('supplybarang', 'App\Http\Controllers\SupplyBarangController');
Route::get('/cetak_pdf/supplybarang', 'App\Http\Controllers\SupplyBarangController@cetak_pdf');

//KERUSAKAN
Route::resource('returnbarang', 'App\Http\Controllers\ReturnBarangController');
Route::get('/cetak_pdf/returnbarang', 'App\Http\Controllers\ReturnBarangController@cetak_pdf');

// //MENU
Route::get('/menu/get', 'App\Http\Controllers\MenuMakananController@byKategori')->name('menu.bykategori');
Route::resource('menumakanan', 'App\Http\Controllers\MenuMakananController');
Route::get('/cetak_pdf/menumakanan', 'App\Http\Controllers\MenuMakananController@cetak_pdf');

//KASIR
Route::resource('/transaksi', 'App\Http\Controllers\TransaksiController');
Route::get('/cetak_pdf/transaksi', 'App\Http\Controllers\TransaksiController@cetak_pdf');

// //ABSENSI
Route::resource('/absensi', 'App\Http\Controllers\AbsensiController');

//PEMILIK
Route::resource('/p_supplier', 'App\Http\Controllers\P_SupController');
Route::resource('/p_menumakanan', 'App\Http\Controllers\P_MenuController');
// Route::resource('/pemasukan', 'App\Http\Controllers\P_PemasukanController');
Route::get('/pemasukan/{cabang}/{bulan}/{tahun}', 'App\Http\Controllers\P_PemasukanController@index')->name('getPemasukan');
Route::resource('/pengeluaran', 'App\Http\Controllers\P_PengeluaranController');

Route::get('/grafik/{tahun}', 'App\Http\Controllers\P_GrafikController@index');
Route::get('/grafikMakananFavorit', 'App\Http\Controllers\P_grafikmmController@index')->name('grafikmm');
Route::get('/getDataGrafikPendapata ', 'App\Http\Controllers\P_GrafikController@getDataGrafikPendapata')->name('getDataGrafikPendapata');

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;
    protected $table = 'suppliers';
    protected $primaryKey = 'supkode';
    public $incrementing = false;
    protected $fillable = [
        'supkode','supnama'
    ];

}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Supplier;
use PDF;
use RealRashid\SweetAlert\Facades\Alert;


class SupplierController extends Controller
{

    public function index()
    {
        $supplier = Supplier::latest()->get();
    
        return view('admin.supplier.index',compact('supplier'));  
    }

    public function cetak_pdf()
    {
        // return 'iii';
    	$supplier = Supplier::all();
        // return view('admin/supplier/sup_pdf',['supplier'=>$supplier]);
    	$pdf = PDF::loadview('admin/supplier/sup_pdf',['supplier'=>$supplier]);
    	return $pdf->download('daftar-supplier.pdf');
    }

    public function create()
    {
        return view('admin.supplier.create');

    }

    
    public function store(Request $request)
    {
        $request->validate([
            'supkode' => 'required',
            'supnama' => 'required',
        ]);
     
        $cek = Supplier::find($request['supkode']);
        if($cek == ""){
        Supplier::create($request->all());
            Alert::success('Sukses', 'Data Supplier Berhasil Ditambahkan');
            return redirect()->route('supplier.index');
        }else{
            Alert::error('Gagal', 'Data Supplier Gagal Ditambahkan');
            return redirect()->route('supplier.index');
        }
        
                    
    }

   
    public function show($id)
    {
        //
    }

    public function search(Request $request)
    {
        $search = $request->get('search');
        $supplier = Supplier::latest()->paginate(5);
        return view('admin.supplier.index',compact('supplier'))
        ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    
    public function edit($supkode)
    {
        $supplier = Supplier::findOrFail($supkode);
        return view('admin.supplier.edit',compact('supplier'));
    }

    
    public function update(Request $request, Supplier $supplier)
    {
        $request->validate([
            'supnama' => 'required',
        ]);
    
        $supplier->update($request->all());
    
        Alert::success('Sukses', 'Data Supplier Berhasil Diubah');
            return redirect()->route('supplier.index');
    }

   
    public function destroy(Supplier $supplier)
    {
        $supplier->delete();
    
        Alert::success('Sukses', 'Data Supplier Berhasil Dihapus');
            return redirect()->route('supplier.index');
    }

   
}

resources/views/admin/supplier/create.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Tambah Data Supplier</h4></center>
@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
    </div>
@endif
   
<form action="{{ route('supplier.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Supplier:</strong>
                <input type="text" name="supkode" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Supplier:</strong>
                <input type="text" name="supnama" class="form-control" placeholder="">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/admin/supplier/edit.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Edit Supplier</h4></center>
@endsection

@section('content')
@if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
        </div>
    @endif
  
    <form action="{{ route('supplier.update',$supplier->supkode) }}" method="POST">
        @csrf
        @method('PUT')
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Kode Supplier:</strong>
                <input type="text" readonly name="kodesup" class="form-control" placeholder=" " value="{{ $supplier->supkode }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Supplier:</strong>
                <input type="text" name="supnama" class="form-control" placeholder="" value="{{ $supplier->supnama }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
    </form>
@endsection

resources/views/admin/supplier/index.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Daftar Supplier</h4></center>
@endsection

@section('content')

    <div class="row">
        <div class="container" style="margin-left: 15px;">
                <a class="btn btn-info btn-sm" href="{{ route('supplier.create') }}">Tambah Supplier</a>
                <a class="btn btn-danger btn-sm" href="{{ url('/cetak_pdf/supplier') }}">Cetak</a>
        </div>
    </div>
    
    </br>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    
    <table id ="datasup" class="table table-borderes table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Kode Supplier</th>
                <th scope="col">Nama Supplier</th>
                <th scope="col">AKSI</th>
            </tr>
        </thead>
        <tbody>
            @php $i=1 @endphp
            @foreach ($supplier as $sup)
            <tr>
                <td>{{ $i++ }}</td>
                <td>{{ $sup->supkode }}</td>
                <td>{{ $sup->supnama }}</td>
                <td>
                        <form action="{{ route('supplier.destroy', $sup->supkode)}}" method="post">
                        <a href="{{ route('supplier.edit', $sup->supkode)}}" <button type="submit" class="btn btn-warning btn-sm btn-edit" title="Edit"><i class="fa fa-edit"></i></button></a>
                        @csrf
                        @method('DELETE')      
                        <button type="submit" class="btn btn-danger btn-sm btn-flat" title="Hapus"><i class="fa fa-trash"></i></button>                    
                        </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>  
@endsection

@push('script')
<script>
$(document).ready(function () {
    $('#datasup').dataTable();
});
</script>
@endpush

resources/views/admin/supplier/sup_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Daftar Supplier</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Daftar Supplier</h4>
		<h5>Angkringan Panjer Wengi</h4>
	</center>

	<table class='table table-bordered'>
		<thead>
			<tr>
				<th>No</th>
				<th>Kode Supplier</th>
				<th>Nama</th>
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
			@foreach($supplier as $sup)
			<tr>
				<td>{{ $i++ }}</td>
				<td>{{ $sup->supkode}}</td>
				<td>{{ $sup->supnama}}</td>
			</tr>
			@endforeach
		</tbody>
	</table>

</body>
</html>