routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// LOGIN
Route::get('login','App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login','App\Http\Controllers\AuthController@proses_login')->name('proses_login');

Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['cek_login:admin']], function () {
        Route::get('admin','App\Http\Controllers\AdminController@index')->name('admin');
        Route::get('adminkar', 'App\Http\Controllers\KaryawanController@adminkar')->name('adminkar');
        Route::resource('datakar', 'App\Http\Controllers\KaryawanController');
    }); 
    Route::group(['middleware' => ['cek_login:pemilik']], function () {
        Route::get('pemilik','App\Http\Controllers\PemilikController@index')->name('pemilik');
    }); 
    Route::group(['middleware' => ['cek_login:karyawan']], function () {
        Route::get('/karyawan', function () {
            return view('karyawan.karyawan');
        })->name('karyawan');
    }); 
    Route::group(['middleware' => ['cek_login:kasir']], function () {
        Route::get('kasir','App\Http\Controllers\KasirController@index')->name('kasir');
    });   
});

//REGISTER
Route::get('register', 'App\Http\Controllers\RegisterController@create')->name('register');
Route::post('register', 'App\Http\Controllers\RegisterController@store')->name('register');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('bagian', 'App\Http\Controllers\BagianController');

//  AKUN
Route::get('akun', 'App\Http\Controllers\AkunController@index')->name('akun');

//SUPPLIER
Route::resource('supplier', 'App\Http\Controllers\SupplierController');
Route::get('/cetak_pdf/supplier', 'App\Http\Controllers\SupplierController@cetak_pdf');

//SUPPLYBARANG
Route::resource('supplybarang', 'App\Http\Controllers\SupplyBarangController');
Route::get('/cetak_pdf/supplybarang', 'App\Http\Controllers\SupplyBarangController@cetak_pdf');

//KERUSAKAN
Route::resource('returnbarang', 'App\Http\Controllers\ReturnBarangController');
Route::get('/cetak_pdf/returnbarang', 'App\Http\Controllers\ReturnBarangController@cetak_pdf');

// //MENU
Route::get('/menu/get', 'App\Http\Controllers\MenuMakananController@byKategori')->name('menu.bykategori');
Route::resource('menumakanan', 'App\Http\Controllers\MenuMakananController');
Route::get('/cetak_pdf/menumakanan', 'App\Http\Controllers\MenuMakananController@cetak_pdf');

//KASIR
Route::resource('/transaksi', 'App\Http\Controllers\TransaksiController');
Route::get('/cetak_pdf/transaksi', 'App\Http\Controllers\TransaksiController@cetak_pdf');

// //ABSENSI
Route::resource('/absensi', 'App\Http\Controllers\AbsensiController');

//PEMILIK
Route::resource('/p_supplier', 'App\Http\Controllers\P_SupController');
Route::resource('/p_menumakanan', 'App\Http\Controllers\P_MenuController');
// Route::resource('/pemasukan', 'App\Http\Controllers\P_PemasukanController');
Route::get('/pemasukan/{cabang}/{bulan}/{tahun}', 'App\Http\Controllers\P_PemasukanController@index')->name('getPemasukan');
Route::resource('/pengeluaran', 'App\Http\Controllers\P_PengeluaranController');

Route::get('/grafik/{tahun}', 'App\Http\Controllers\P_GrafikController@index');
Route::get('/grafikMakananFavorit', 'App\Http\Controllers\P_grafikmmController@index')->name('grafikmm');
Route::get('/getDataGrafikPendapata ', 'App\Http\Controllers\P_GrafikController@getDataGrafikPendapata')->name('getDataGrafikPendapata');

app/Models/Bagian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Karyawan;

class Bagian extends Model
{
    use HasFactory;

    protected $table = 'bagians';
    protected $primaryKey='bagid';
    protected $fillable = [
        'bagnama', 'bagpok'
    ];

}

app/Http/Controllers/BagianController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
// use Illuminate\Support\Facades\DB;
use App\Models\Bagian;

class BagianController extends Controller
{
    public function index()
    {
        $bagian = Bagian::latest()->paginate(5);
    
        return view('admin.bagian.index',compact('bagian'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('admin.bagian.create');
    }

    public function store(Request $request)
    {
         $request->validate([
            'bagnama' => 'required',
            'bagpok' => 'required',
        ]);
    
        Bagian::create($request->all());
     
        return redirect()->route('bagian.index')
                        ->with('success','Bagian created successfully.');
    }


    public function show(Bagian $bagian)
    {
       //
    }


    public function edit($bagid)
    {
        $bagian = Bagian::findOrFail($bagid);
        return view('admin.bagian.edit',compact('bagian'));
    }

    public function update(Request $request, Bagian $bagian)
    {
        $request->validate([
            'bagnama' => 'required',
            'bagpok' => 'required',
        ]);
    
        $bagian->update($request->all());
    
        return redirect()->route('bagian.index')
                        ->with('success','Bagian updated successfully');
    }

    public function destroy(Bagian $bagian)
    {
        $bagian->delete();
    
        return redirect()->route('bagian.index')
                        ->with('success','Bagian deleted successfully');
    }

   
}

resources/views/admin/bagian/create.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Tambah Bagian</h4></center>
@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
    </div>
@endif
   
<form action="{{ route('bagian.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Bagian:</strong>
                <input type="text" name="bagnama" class="form-control" placeholder="Contoh : Kasir">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Gaji Pokok:</strong>
                <input type="text" name="bagpok" class="form-control" placeholder="Contoh : 1000000">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/admin/bagian/edit.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Edit Bagian</h4></center>
@endsection

@section('content')
@if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
        </div>
    @endif
  
    <form action="{{ route('bagian.update',$bagian->bagid) }}" method="POST">
        @csrf
        @method('PUT')
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama Bagian:</strong>
                <input type="text" name="bagnama" class="form-control" placeholder="Contoh : Kasir " value="{{ $bagian->bagnama }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Gaji Pokok:</strong>
                <input type="text" name="bagpok" class="form-control" placeholder="Contoh : 1000000" value="{{ $bagian->bagpok }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
    </form>
@endsection

resources/views/admin/bagian/index.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Halaman Bagian</h4></center>
@endsection

@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-info btn-sm" href="{{ route('bagian.create') }}">Tambah Bagian</a>
            </div>
        </div>
    </div>

    </br>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-borderes table-striped table-hover">
        <tr>
            <th>No</th>
            <th>Nama Bagian</th>
            <th>Gaji Pokok</th>
            <th width="280x">AKSI</th>
        </tr>
        @foreach ($bagian as $bag)
        <tr>
            <td>{{ $bag->bagid }}</td>
            <td>{{ $bag->bagnama }}</td>
            <td>{{ $bag->bagpok }}</td>
            <td>
                <form action="{{ route('bagian.destroy', $bag->bagid)}}" method="post">
                <a href="{{ route('bagian.edit', $bag->bagid)}}" class="btn btn-warning btn-sm">Edit</a>
                    @csrf
                    @method('DELETE')      
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>  
@endsection