routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// LOGIN
Route::get('login','App\Http\Controllers\AuthController@index')->name('login');
Route::post('proses_login','App\Http\Controllers\AuthController@proses_login')->name('proses_login');

Route::get('logout', 'App\Http\Controllers\AuthController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::group(['middleware' => ['cek_login:admin']], function () {
        Route::get('admin','App\Http\Controllers\AdminController@index')->name('admin');
        Route::get('adminkar', 'App\Http\Controllers\KaryawanController@adminkar')->name('adminkar');
        Route::resource('datakar', 'App\Http\Controllers\KaryawanController');
    }); 
    Route::group(['middleware' => ['cek_login:pemilik']], function () {
        Route::get('pemilik','App\Http\Controllers\PemilikController@index')->name('pemilik');
    }); 
    Route::group(['middleware' => ['cek_login:karyawan']], function () {
        Route::get('/karyawan', function () {
            return view('karyawan.karyawan');
        })->name('karyawan');
    }); 
    Route::group(['middleware' => ['cek_login:kasir']], function () {
        Route::get('kasir','App\Http\Controllers\KasirController@index')->name('kasir');
    });   
});

//REGISTER
Route::get('register', 'App\Http\Controllers\RegisterController@create')->name('register');
Route::post('register', 'App\Http\Controllers\RegisterController@store')->name('register');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('bagian', 'App\Http\Controllers\BagianController');

//  AKUN
Route::get('akun', 'App\Http\Controllers\AkunController@index')->name('akun');

//SUPPLIER
Route::resource('supplier', 'App\Http\Controllers\SupplierController');
Route::get('/cetak_pdf/supplier', 'App\Http\Controllers\SupplierController@cetak_pdf');

//SUPPLYBARANG
Route::resource('supplybarang', 'App\Http\Controllers\SupplyBarangController');
Route::get('/cetak_pdf/supplybarang', 'App\Http\Controllers\SupplyBarangController@cetak_pdf');

//KERUSAKAN
Route::resource('returnbarang', 'App\Http\Controllers\ReturnBarangController');
Route::get('/cetak_pdf/returnbarang', 'App\Http\Controllers\ReturnBarangController@cetak_pdf');

// //MENU
Route::get('/menu/get', 'App\Http\Controllers\MenuMakananController@byKategori')->name('menu.bykategori');
Route::resource('menumakanan', 'App\Http\Controllers\MenuMakananController');
Route::get('/cetak_pdf/menumakanan', 'App\Http\Controllers\MenuMakananController@cetak_pdf');

//KASIR
Route::resource('/transaksi', 'App\Http\Controllers\TransaksiController');
Route::get('/cetak_pdf/transaksi', 'App\Http\Controllers\TransaksiController@cetak_pdf');

// //ABSENSI
Route::resource('/absensi', 'App\Http\Controllers\AbsensiController');

//PEMILIK
Route::resource('/p_supplier', 'App\Http\Controllers\P_SupController');
Route::resource('/p_menumakanan', 'App\Http\Controllers\P_MenuController');
// Route::resource('/pemasukan', 'App\Http\Controllers\P_PemasukanController');
Route::get('/pemasukan/{cabang}/{bulan}/{tahun}', 'App\Http\Controllers\P_PemasukanController@index')->name('getPemasukan');
Route::resource('/pengeluaran', 'App\Http\Controllers\P_PengeluaranController');

Route::get('/grafik/{tahun}', 'App\Http\Controllers\P_GrafikController@index');
Route::get('/grafikMakananFavorit', 'App\Http\Controllers\P_grafikmmController@index')->name('grafikmm');
Route::get('/getDataGrafikPendapata ', 'App\Http\Controllers\P_GrafikController@getDataGrafikPendapata')->name('getDataGrafikPendapata');

app/Models/MenuMakanan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MenuMakanan extends Model
{
    use HasFactory;
    protected $table = 'menu_makanans';
    protected $primaryKey = 'menukd';
    public $incrementing = false;
    protected $fillable = [
        'menukd',
        'menunm',
        'stok',
        'hargajual'
    ];
}

app/Http/Controllers/MenuMakananController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MenuMakanan;
use RealRashid\SweetAlert\Facades\Alert;


class MenuMakananController extends Controller
{
    
    public function index()
    {
        $menumakanan = MenuMakanan::latest()->get();
    
        return view('admin.menumakanan.index',compact('menumakanan'));
    }

    public function cetak_pdf(){
        $menumakanan = MenuMakanan::all();
    	$pdf = PDF::loadview('admin/menumakanan/menu_pdf',['menumakanan'=>$menumakanan]);
    	return $pdf->download('daftar-menumakanan.pdf');
    }

    public function create()
    {
         return view('admin.menumakanan.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'menukd' => 'required',
            'menunm' => 'required',
            'stok' => 'required',
            'hargajual' => 'required',
        ]);

        $cek = MenuMakanan::find($request['menukd']);
        if($cek == ""){
        MenuMakanan::create($request->all());
        Alert::success('Sukses', 'Data Menu Makanan Berhasil ditambahkan');
            return redirect()->route('menumakanan.index');
        }else{
            Alert::error('Gagal', 'Data Menu Makanan Gagal Ditambahkan');
            return redirect()->route('menumakanan.index');
        }
    }

    public function byKategori(Request $request){
        $menu = MenuMakanan::where('kategori', $request->kategori)
        ->where('menunm', 'like', '%' . $request->q . '%')
        ->get();

        // dd($menu);

        return view('partials.menubykategori', compact('menu'));
    }


    public function show($id)
    {
        //
    }


    public function edit($menukd)
    {
        // $supplybarang = SupplyBarang::all();
        $menumakanan = MenuMakanan::findOrFail($menukd);
        return view('admin.menumakanan.edit',compact('menumakanan'));

        // return view('admin.menumakanan.edit',compact('menumakanan','supplybarang'));
    }


    public function update(Request $request, MenuMakanan $menumakanan)
    {
        $request->validate([
            'menukd' => 'required',
            'menunm' => 'required',
            'stok' => 'required',
            'hargajual' => 'required',
        ]);

        $menumakanan->update($request->all());

        return redirect()->route('menumakanan.index')
                        ->with('success','Menu makanan berhasil diubah.');

    }


    public function destroy(MenuMakanan $menumakanan)
    {
        $menumakanan->delete();
    
        return redirect()->route('menumakanan.index')
                        ->with('success','Data Menu Makanan Berhasil dihapus deleted successfully');

    }
}

resources/views/admin/menumakanan/create.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Tambah Menu Makanan</h4></center>
@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
    </div>
@endif
   
<form action="{{ route('menumakanan.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <strong>Kode Menu</strong>
                <input type="text" name="menukd" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <strong>Nama Menu</strong>
                <input type="text" name="menunm" class="form-control" placeholder="">
            </div>
        </div>
        
        <div class="col-md-6">
            <div class="form-group">
                <strong>Stok</strong>
                <input type="text" name="stok" class="form-control" placeholder="">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <strong>Harga Jual</strong>
                <input type="text" name="hargajual" class="form-control" placeholder="">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/admin/menumakanan/edit.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Edit Data Menu Makanan</h4></center>
@endsection

@section('content')
@if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
        </div>
    @endif

    <form action="{{ route('menumakanan.update', $menumakanan->menukd) }}" method="POST">
    @csrf    
    @method('PUT')
  
     <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <strong>Kode Menu</strong>
                <input type="text" readonly name="menukd" class="form-control" value="{{ $menumakanan->menukd }}">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <strong>Nama Menu</strong>
                <input type="text" name="menunm" class="form-control" value="{{ $menumakanan->menunm }}">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <strong>Stok</strong>
                <input type="text" name="stok" class="form-control" value="{{ $menumakanan->stok }}">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <strong>Harga Jual</strong>
                <input type="text" name="hargajual" class="form-control" value="{{ $menumakanan->hargajual }}">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

    </form>
@endsection

resources/views/admin/menumakanan/index.blade.php
@extends('layout')
@section('title','Halaman Admin')
@section('header')
<center><h4>Daftar Menu Makanan</h4></center>
@endsection

@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <a class="btn btn-info btn-sm" href="{{ route('menumakanan.create') }}">Tambah Data Menu Makanan</a>
            </div>
        </div>
    </div>

    </br>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table id = "datamenu" class="table table-borderes table-striped table-hover">
        <thead>
            <tr>
                <th>No</th>
                <th>Kode Menu</th>
                <th>Menu</th>
                <th>Stok</th>
                <th>Harga Jual</th>
                <!-- <th>Harga Beli</th> -->
                <th>AKSI</th>
            </tr>
        </thead>
        <tbody>
            @php $i=1 @endphp
            @foreach ($menumakanan as $mm)
            <tr>
                <td>{{ $i++ }}</td>
                <td>{{ $mm->menukd }}</td>
                <td>{{ $mm->menunm }}</td>
                <td>{{ $mm->stok }}</td>
                <td>{{ $mm->hargajual }}</td>
                <td>
                    <form action="{{ route('menumakanan.destroy', $mm->menukd )}}" method="post">
                    <a href="{{ route('menumakanan.edit', $mm->menukd )}}" <button type="submit" class="btn btn-warning btn-sm btn-edit" title="Edit"><i class="fa fa-edit"></i></button></a>
                        @csrf
                        @method('DELETE')      
                        <button type="submit" class="btn btn-danger btn-sm btn-flat" title="Hapus"><i class="fa fa-trash"></i></button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>  
@endsection

@push('script')
<script>
$(document).ready(function () {
    $('#datamenu').dataTable();
});
</script>
@endpush

resources/views/admin/menumakanan/menu_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Daftar Supplier</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Daftar Supplier</h4>
		<h5>Angkringan Panjer Wengi</h4>
	</center>

	<table class='table table-bordered'>
		<thead>
			<tr>
				<th>No</th>
				<th>Kode Supplier</th>
				<th>Nama</th>
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
			@foreach($supplier as $sup)
			<tr>
				<td>{{ $i++ }}</td>
				<td>{{ $sup->supkode}}</td>
				<td>{{ $sup->supnama}}</td>
			</tr>
			@endforeach
		</tbody>
	</table>

</body>
</html>